# ██╗  ██╗██╗██╗     ██╗     ███████╗██████╗
# ██║ ██╔╝██║██║     ██║     ██╔════╝██╔══██╗
# █████╔╝ ██║██║     ██║     █████╗  ██████╔╝
# ██╔═██╗ ██║██║     ██║     ██╔══╝  ██╔══██╗
# ██║  ██╗██║███████╗███████╗███████╗██║  ██║
# ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝
#
# ██╗  ██╗██╗      ██████╗ ██╗    ██╗███╗   ██╗███████╗
# ██║ ██╔╝██║     ██╔═══██╗██║    ██║████╗  ██║╚══███╔╝
# █████╔╝ ██║     ██║   ██║██║ █╗ ██║██╔██╗ ██║  ███╔╝
# ██╔═██╗ ██║     ██║   ██║██║███╗██║██║╚██╗██║ ███╔╝
# ██║  ██╗███████╗╚██████╔╝╚███╔███╔╝██║ ╚████║███████╗
# ╚═╝  ╚═╝╚══════╝ ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═══╝╚══════╝

[window]
opacity = 0.8333333

[colors]
[colors.primary]
background = "#0b0a10"
foreground = "#3cfaff"

[colors.normal]
black   = "#0b0a10"
red     = "#ff3c8e"
green   = "#2dff6a"
yellow  = "#ffe347"
blue    = "#4b6cff"
magenta = "#b96bff"
cyan    = "#ff4fd8"
white   = "#3cfaff"

[colors.bright]
black   = "#7a74a0"
red     = "#ff3c8e"
green   = "#2dff6a"
yellow  = "#ffe347"
blue    = "#4b6cff"
magenta = "#b96bff"
cyan    = "#ff4fd8"
white   = "#e6e3ff"

[colors.cursor]
text   = "#0b0a10"
cursor = "#3cfaff"

[colors.selection]
text = "#1a0020"
background = "#ff4fd8"

#  ,-----. ,--.   ,--.     ,--.       ,--.          ,--.
# '  .-.  '|  | ,-|  |     |  | ,---. |  |-.  ,---. |  |-.  ,---.
# |  | |  ||  |' .-. |,--. |  || .-. || .-. '| .-. || .-. '| .-. |
# '  '-'  '|  |\ `-' ||  '-'  /' '-' '| `-' |' '-' '| `-' |' '-' '
#  `-----' `--' `---'  `-----'  `---'  `---'  `---'  `---'  `---'
