# ██╗  ██╗██╗██╗     ██╗     ███████╗██████╗
# ██║ ██╔╝██║██║     ██║     ██╔════╝██╔══██╗
# █████╔╝ ██║██║     ██║     █████╗  ██████╔╝
# ██╔═██╗ ██║██║     ██║     ██╔══╝  ██╔══██╗
# ██║  ██╗██║███████╗███████╗███████╗██║  ██║
# ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝
#
# ██╗  ██╗██╗      ██████╗ ██╗    ██╗███╗   ██╗███████╗
# ██║ ██╔╝██║     ██╔═══██╗██║    ██║████╗  ██║╚══███╔╝
# █████╔╝ ██║     ██║   ██║██║ █╗ ██║██╔██╗ ██║  ███╔╝
# ██╔═██╗ ██║     ██║   ██║██║███╗██║██║╚██╗██║ ███╔╝
# ██║  ██╗███████╗╚██████╔╝╚███╔███╔╝██║ ╚████║███████╗
# ╚═╝  ╚═╝╚══════╝ ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═══╝╚══════╝

# foot.ini
# By OldJobobo (https://github.com/OldJobobo)
#

[colors-dark]
alpha = 0.8333333

foreground = 3cfaff
background = 0b0a10

cursor = 0b0a10 3cfaff
selection-foreground = 1a0020
selection-background = ff4fd8

# regular (ANSI 0-7)
regular0 = 0b0a10
regular1 = ff3c8e
regular2 = 2dff6a
regular3 = ffe347
regular4 = 4b6cff
regular5 = b96bff
regular6 = ff4fd8
regular7 = e6e3ff

# bright (ANSI 8-15)
bright0 = 7a74a0
bright1 = ff3c8e
bright2 = 2dff6a
bright3 = ffe347
bright4 = 4b6cff
bright5 = b96bff
bright6 = ff4fd8
bright7 = 3cfaff

#  ,-----. ,--.   ,--.     ,--.       ,--.          ,--.
# '  .-.  '|  | ,-|  |     |  | ,---. |  |-.  ,---. |  |-.  ,---.
# |  | |  ||  |' .-. |,--. |  || .-. || .-. '| .-. || .-. '| .-. |
# '  '-'  '|  |\ `-' ||  '-'  /' '-' '| `-' |' '-' '| `-' |' '-' '
#  `-----' `--' `---'  `-----'  `---'  `---'  `---'  `---'  `---'