# ██╗  ██╗██╗██╗     ██╗     ███████╗██████╗
# ██║ ██╔╝██║██║     ██║     ██╔════╝██╔══██╗
# █████╔╝ ██║██║     ██║     █████╗  ██████╔╝
# ██╔═██╗ ██║██║     ██║     ██╔══╝  ██╔══██╗
# ██║  ██╗██║███████╗███████╗███████╗██║  ██║
# ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝
#
# ██╗  ██╗██╗      ██████╗ ██╗    ██╗███╗   ██╗███████╗
# ██║ ██╔╝██║     ██╔═══██╗██║    ██║████╗  ██║██╔════╝
# █████╔╝ ██║     ██║   ██║██║ █╗ ██║██╔██╗ ██║███████╗
# ██╔═██╗ ██║     ██║   ██║██║███╗██║██║╚██╗██║╚════██║
# ██║  ██╗███████╗╚██████╔╝╚███╔███╔╝██║ ╚████║███████║
# ╚═╝  ╚═╝╚══════╝ ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═══╝╚══════╝

# Background and foreground colors
background = #0b0a10
foreground = #3cfaff
background-opacity = 0.9333333

# Standard colors
palette = 0=#0b0a10
palette = 1=#ff3c8e
palette = 2=#2dff6a
palette = 3=#ffe347
palette = 4=#4b6cff
palette = 5=#b96bff
palette = 6=#ff4fd8
palette = 7=#e6e3ff

# Bright colors
palette = 8=#7a74a0
palette = 9=#ff3c8e
palette = 10=#2dff6a
palette = 11=#ffe347
palette = 12=#4b6cff
palette = 13=#b96bff
palette = 14=#ff4fd8
palette = 15=#3cfaff

#  ,-----. ,--.   ,--.     ,--.       ,--.          ,--.
# '  .-.  '|  | ,-|  |     |  | ,---. |  |-.  ,---. |  |-.  ,---.
# |  | |  ||  |' .-. |,--. |  || .-. || .-. '| .-. || .-. '| .-. |
# '  '-'  '|  |\ `-' ||  '-'  /' '-' '| `-' |' '-' '| `-' |' '-' '
#  `-----' `--' `---'  `-----'  `---'  `---'  `---'  `---'  `---'