-- Generated by scripts/hypr2lua.
-- Source: /home/oldjobobo/Projects/themes/omarchy-killer-klownz-theme/hyprland.conf

local groupBorderColor = "rgb(b96bff)"

hl.config({
  general = {
    border_size = 7,
    col = {
      active_border = {
        colors = { "rgba(ff3c8eff)", "rgba(ff4fd8ff)", "rgba(b96bffff)", "rgba(4b6cffff)", "rgba(2dff6aff)", "rgba(ffe347ff)", "rgba(ff3c8eff)" },
        angle = 45,
      },
      inactive_border = "rgba(1a002066)",
    },
  },
  group = {
    col = {
      border_active = groupBorderColor,
    },
  },
  animations = {
    enabled = true,
  },
  decoration = {
    rounding = 0,
    active_opacity = 0.999,
    inactive_opacity = 0.9777,
    shadow = {
      enabled = true,
      range = 45,
      render_power = 3,
      offset = "0 5",
      color = "rgba(ff4fd8bb)",
      color_inactive = "rgba(1a002055)",
    },
    blur = {
      enabled = true,
      size = 8,
      passes = 3,
      new_optimizations = true,
      noise = 0.03,
      contrast = 0.95,
      brightness = 0.83,
      vibrancy = 0.23,
      vibrancy_darkness = 0.75,
      xray = true,
    },
  },
})

hl.curve("klownPop", { type = "bezier", points = { { 0.18, 1.20 }, { 0.35, 1.00 } } })
hl.curve("klownVanish", { type = "bezier", points = { { 0.55, 0.00 }, { 0.80, 0.00 } } })
hl.curve("circuitPulse", { type = "bezier", points = { { 0.37, 0.00 }, { 0.63, 1.00 } } })
hl.curve("candyFlash", { type = "bezier", points = { { 0.00, 0.80 }, { 0.40, 1.00 } } })
hl.curve("cosmicSlide", { type = "bezier", points = { { 0.65, 0.00 }, { 0.35, 1.00 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 4,
  bezier = "klownPop",
  style = "slide",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 3,
  bezier = "klownVanish",
  style = "popin 80%",
})
hl.animation({
  leaf = "border",
  enabled = true,
  speed = 6,
  bezier = "circuitPulse",
})
hl.animation({
  leaf = "borderangle",
  enabled = true,
  speed = 80,
  bezier = "candyFlash",
  style = "loop",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 3,
  bezier = "candyFlash",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 4,
  bezier = "cosmicSlide",
  style = "slide",
})

hl.layer_rule({
  blur = false,
  match = {
    namespace = "walker",
  },
})
hl.layer_rule({
  blur = false,
  match = {
    namespace = "notifications",
  },
})
hl.layer_rule({
  blur = false,
  match = {
    namespace = "swayosd",
  },
})
hl.window_rule({
  name = "float-rounding",
  rounding = 14,
  match = {
    float = true,
  },
})
