# ██╗  ██╗██╗██╗     ██╗     ███████╗██████╗
# ██║ ██╔╝██║██║     ██║     ██╔════╝██╔══██╗
# █████╔╝ ██║██║     ██║     █████╗  ██████╔╝
# ██╔═██╗ ██║██║     ██║     ██╔══╝  ██╔══██╗
# ██║  ██╗██║███████╗███████╗███████╗██║  ██║
# ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝
#
# ██╗  ██╗██╗      ██████╗ ██╗    ██╗███╗   ██╗███████╗
# ██║ ██╔╝██║     ██╔═══██╗██║    ██║████╗  ██║██╔════╝
# █████╔╝ ██║     ██║   ██║██║ █╗ ██║██╔██╗ ██║███████╗
# ██╔═██╗ ██║     ██║   ██║██║███╗██║██║╚██╗██║╚════██║
# ██║  ██╗███████╗╚██████╔╝╚███╔███╔╝██║ ╚████║███████║
# ╚═╝  ╚═╝╚══════╝ ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═══╝╚══════╝

$color = rgba(10, 0, 5, 1)
$inner_color = rgba(10, 0, 5, 0.66)
$outer_color = rgba(245, 194, 231, 1)
$font_color = rgba(60, 250, 255, 1)
$placeholder_color = rgba(60, 250, 255, 0.5)
$check_color = rgba(45, 255, 106, 1)

#  ,-----. ,--.   ,--.     ,--.       ,--.          ,--.
# '  .-.  '|  | ,-|  |     |  | ,---. |  |-.  ,---. |  |-.  ,---.
# |  | |  ||  |' .-. |,--. |  || .-. || .-. '| .-. || .-. '| .-. |
# '  '-'  '|  |\ `-' ||  '-'  /' '-' '| `-' |' '-' '| `-' |' '-' '
#  `-----' `--' `---'  `-----'  `---'  `---'  `---'  `---'  `---'