# ██╗  ██╗██╗██╗     ██╗     ███████╗██████╗
# ██║ ██╔╝██║██║     ██║     ██╔════╝██╔══██╗
# █████╔╝ ██║██║     ██║     █████╗  ██████╔╝
# ██╔═██╗ ██║██║     ██║     ██╔══╝  ██╔══██╗
# ██║  ██╗██║███████╗███████╗███████╗██║  ██║
# ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝
#
# ██╗  ██╗██╗      ██████╗ ██╗    ██╗███╗   ██╗███████╗
# ██║ ██╔╝██║     ██╔═══██╗██║    ██║████╗  ██║╚══███╔╝
# █████╔╝ ██║     ██║   ██║██║ █╗ ██║██╔██╗ ██║  ███╔╝
# ██╔═██╗ ██║     ██║   ██║██║███╗██║██║╚██╗██║ ███╔╝
# ██║  ██╗███████╗╚██████╔╝╚███╔███╔╝██║ ╚████║███████╗
# ╚═╝  ╚═╝╚══════╝ ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═══╝╚══════╝

background            #0b0a10
foreground            #3cfaff
background_opacity    0.8333333
selection_foreground  #1a0020
selection_background  #ff4fd8

# black
color0  #0b0a10
color8  #7a74a0

# red
color1  #ff3c8e
color9  #ff3c8e

# green
color2  #2dff6a
color10 #2dff6a

# yellow
color3  #ffe347
color11 #ffe347

# blue
color4  #4b6cff
color12 #4b6cff

# magenta
color5  #b96bff
color13 #b96bff

#cyan
color6  #ff4fd8
color14 #ff4fd8

#white
color7  #3cfaff
color15 #e6e3ff

#  ,-----. ,--.   ,--.     ,--.       ,--.          ,--.
# '  .-.  '|  | ,-|  |     |  | ,---. |  |-.  ,---. |  |-.  ,---.
# |  | |  ||  |' .-. |,--. |  || .-. || .-. '| .-. || .-. '| .-. |
# '  '-'  '|  |\ `-' ||  '-'  /' '-' '| `-' |' '-' '| `-' |' '-' '
#  `-----' `--' `---'  `-----'  `---'  `---'  `---'  `---'  `---'
